modLoader="javafml"
license="Apache-2.0"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Trinsdar/FabricBiomeApiReforged/issues"

[[mods]]
modId="fabric-biome-api"
version="${version}"
displayName="Fabric BiomeApi Reforged"
displayURL="https://github.com/Trinsdar/FabricBiomeApiReforged"
credits="Fabric team for creating fabric and this api, all other contributers who contributed to the original over the years."
authors="Trinsdar"
description='''Fabric's Biome api ported to forge. I did this cause the forge api just isn't powerful enough for what I need.'''
[[dependencies.fabric-biome-api]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.fabric-biome-api]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="AFTER"
    side="BOTH"