modLoader="javafml"
license="Apache-2.0"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Trinsdar/NetherEndBiomeInjector/issues"

[[mods]]
modId="nebi"
version="${version}"
displayName="Nether End Biome Injector"
displayURL="https://github.com/Trinsdar/NetherEndBiomeInjector"
credits="Fabric team for creating fabric and this api, all other contributers who contributed to the original over the years."
authors="Trinsdar"
description='''An api to add nether and end biomes to their respective dimensions to generate'''
[[dependencies.nebi]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.nebi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="AFTER"
    side="BOTH"